os: linux
dist: bionic
language: go
go:
  - 1.14
go_import_path: github.com/zennittians/intelchain
env:
  - TEST="make"
  - TEST="bash ./scripts/travis_go_checker.sh"
  - TEST="bash ./scripts/travis_rpc_checker.sh"
  - TEST="bash ./scripts/travis_rosetta_checker.sh"
install:
  # default working directory with source code is automatically set to
  #   /home/travis/gopath/src/github.com/zennittians/intelchain
  # https://docs.travis-ci.com/user/languages/go/#go-import-path
  - git clone https://github.com/zennittians/mcl.git $HOME/gopath/src/github.com/zennittians/mcl
  - git clone https://github.com/zennittians/bls.git $HOME/gopath/src/github.com/zennittians/bls
  - (cd $HOME/gopath/src/github.com/zennittians/mcl; make -j4)
  - (cd $HOME/gopath/src/github.com/zennittians/bls; make BLS_SWAP_G=1 -j4)
  - make go-get
  - scripts/install_build_tools.sh
script:
  - ${TEST}
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
